// Mocks generated by Mockito 5.4.6 from annotations
// in ecommerce/test/features/product/data/repositories/product_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ecommerce/core/platform/network_info.dart' as _i7;
import 'package:ecommerce/features/product/data/data_sources/local_data_source.dart'
    as _i6;
import 'package:ecommerce/features/product/data/data_sources/remote_data_source.dart'
    as _i4;
import 'package:ecommerce/features/product/data/models/product_model.dart'
    as _i2;
import 'package:ecommerce/features/product/domain/entities/product.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductModel_0 extends _i1.SmartFake implements _i2.ProductModel {
  _FakeProductModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProduct_1 extends _i1.SmartFake implements _i3.Product {
  _FakeProduct_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [RemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRemoteDataSource extends _i1.Mock
    implements _i4.RemoteDataSource {
  @override
  _i5.Future<List<Map<String, dynamic>>> fetchProductsFromServer() =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductsFromServer, []),
            returnValue: _i5.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i5.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i5.Future<List<Map<String, dynamic>>>);

  @override
  _i5.Future<Map<String, dynamic>> fetchProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductById, [id]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<_i2.ProductModel> getProductById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [id]),
            returnValue: _i5.Future<_i2.ProductModel>.value(
              _FakeProductModel_0(
                this,
                Invocation.method(#getProductById, [id]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i2.ProductModel>.value(
              _FakeProductModel_0(
                this,
                Invocation.method(#getProductById, [id]),
              ),
            ),
          )
          as _i5.Future<_i2.ProductModel>);

  @override
  _i5.Future<Map<String, dynamic>> createProductOnServer(
    _i2.ProductModel? product,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createProductOnServer, [product]),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> updateProductOnServer(_i2.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductOnServer, [product]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProductFromServer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProductFromServer, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.ProductModel>> getAllProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllProducts, []),
            returnValue: _i5.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i5.Future<List<_i2.ProductModel>>);
}

/// A class which mocks [LocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductLocalDataSource extends _i1.Mock
    implements _i6.LocalDataSource {
  @override
  _i5.Future<List<_i2.ProductModel>> getAllCachedProducts() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCachedProducts, []),
            returnValue: _i5.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
            returnValueForMissingStub: _i5.Future<List<_i2.ProductModel>>.value(
              <_i2.ProductModel>[],
            ),
          )
          as _i5.Future<List<_i2.ProductModel>>);

  @override
  _i5.Future<_i3.Product> getProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductById, [productId]),
            returnValue: _i5.Future<_i3.Product>.value(
              _FakeProduct_1(
                this,
                Invocation.method(#getProductById, [productId]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.Product>.value(
              _FakeProduct_1(
                this,
                Invocation.method(#getProductById, [productId]),
              ),
            ),
          )
          as _i5.Future<_i3.Product>);

  @override
  _i5.Future<void> cacheProducts(List<_i2.ProductModel>? products) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProducts, [products]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> cacheProduct(_i3.Product? product) =>
      (super.noSuchMethod(
            Invocation.method(#cacheProduct, [product]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveProduct(Map<String, dynamic>? productJson) =>
      (super.noSuchMethod(
            Invocation.method(#saveProduct, [productJson]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateProduct(_i2.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  @override
  _i5.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
