// Mocks generated by Mockito 5.4.6 from annotations
// in ecommerce/test/features/product/data/data_sources/product_remote_data_source_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:ecommerce/core/network/http.dart' as _i4;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:socket_io_client/socket_io_client.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultipartRequest_1 extends _i1.SmartFake
    implements _i2.MultipartRequest {
  _FakeMultipartRequest_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSocket_2 extends _i1.SmartFake implements _i3.Socket {
  _FakeSocket_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpResponse_3 extends _i1.SmartFake implements _i4.HttpResponse {
  _FakeHttpResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_4 extends _i1.SmartFake implements Uri {
  _FakeUri_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamedResponse_5 extends _i1.SmartFake
    implements _i2.StreamedResponse {
  _FakeStreamedResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i2.MultipartRequest Function(_i4.HttpMethod, String)
  get multipartRequestFactory =>
      (super.noSuchMethod(
            Invocation.getter(#multipartRequestFactory),
            returnValue: (_i4.HttpMethod __p0, String __p1) =>
                _FakeMultipartRequest_1(
                  this,
                  Invocation.getter(#multipartRequestFactory),
                ),
          )
          as _i2.MultipartRequest Function(_i4.HttpMethod, String));

  @override
  _i3.Socket get socket =>
      (super.noSuchMethod(
            Invocation.getter(#socket),
            returnValue: _FakeSocket_2(this, Invocation.getter(#socket)),
          )
          as _i3.Socket);

  @override
  set authToken(String? token) => super.noSuchMethod(
    Invocation.setter(#authToken, token),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i4.HttpResponse> get(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#get, [url]),
            returnValue: _i5.Future<_i4.HttpResponse>.value(
              _FakeHttpResponse_3(this, Invocation.method(#get, [url])),
            ),
          )
          as _i5.Future<_i4.HttpResponse>);

  @override
  _i5.Future<_i4.HttpResponse> post(
    String? url,
    Map<String, dynamic>? body,
    Map<dynamic, dynamic>? map, {
    required String? bodyText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [url, body, map], {#bodyText: bodyText}),
            returnValue: _i5.Future<_i4.HttpResponse>.value(
              _FakeHttpResponse_3(
                this,
                Invocation.method(
                  #post,
                  [url, body, map],
                  {#bodyText: bodyText},
                ),
              ),
            ),
          )
          as _i5.Future<_i4.HttpResponse>);

  @override
  _i5.Future<_i4.HttpResponse> put(String? url, Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#put, [url, body]),
            returnValue: _i5.Future<_i4.HttpResponse>.value(
              _FakeHttpResponse_3(this, Invocation.method(#put, [url, body])),
            ),
          )
          as _i5.Future<_i4.HttpResponse>);

  @override
  _i5.Future<_i4.HttpResponse> delete(String? url) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [url]),
            returnValue: _i5.Future<_i4.HttpResponse>.value(
              _FakeHttpResponse_3(this, Invocation.method(#delete, [url])),
            ),
          )
          as _i5.Future<_i4.HttpResponse>);

  @override
  _i5.Future<_i4.HttpResponse> uploadFile(
    String? url,
    _i4.HttpMethod? method,
    Map<String, String>? body,
    List<_i4.UploadFile>? files,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadFile, [url, method, body, files]),
            returnValue: _i5.Future<_i4.HttpResponse>.value(
              _FakeHttpResponse_3(
                this,
                Invocation.method(#uploadFile, [url, method, body, files]),
              ),
            ),
          )
          as _i5.Future<_i4.HttpResponse>);
}

/// A class which mocks [MultipartRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockMultipartRequest extends _i1.Mock implements _i2.MultipartRequest {
  MockMultipartRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, String> get fields =>
      (super.noSuchMethod(
            Invocation.getter(#fields),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  List<_i2.MultipartFile> get files =>
      (super.noSuchMethod(
            Invocation.getter(#files),
            returnValue: <_i2.MultipartFile>[],
          )
          as List<_i2.MultipartFile>);

  @override
  int get contentLength =>
      (super.noSuchMethod(Invocation.getter(#contentLength), returnValue: 0)
          as int);

  @override
  set contentLength(int? value) => super.noSuchMethod(
    Invocation.setter(#contentLength, value),
    returnValueForMissingStub: null,
  );

  @override
  String get method =>
      (super.noSuchMethod(
            Invocation.getter(#method),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#method),
            ),
          )
          as String);

  @override
  Uri get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _FakeUri_4(this, Invocation.getter(#url)),
          )
          as Uri);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  bool get persistentConnection =>
      (super.noSuchMethod(
            Invocation.getter(#persistentConnection),
            returnValue: false,
          )
          as bool);

  @override
  bool get followRedirects =>
      (super.noSuchMethod(
            Invocation.getter(#followRedirects),
            returnValue: false,
          )
          as bool);

  @override
  int get maxRedirects =>
      (super.noSuchMethod(Invocation.getter(#maxRedirects), returnValue: 0)
          as int);

  @override
  bool get finalized =>
      (super.noSuchMethod(Invocation.getter(#finalized), returnValue: false)
          as bool);

  @override
  set persistentConnection(bool? value) => super.noSuchMethod(
    Invocation.setter(#persistentConnection, value),
    returnValueForMissingStub: null,
  );

  @override
  set followRedirects(bool? value) => super.noSuchMethod(
    Invocation.setter(#followRedirects, value),
    returnValueForMissingStub: null,
  );

  @override
  set maxRedirects(int? value) => super.noSuchMethod(
    Invocation.setter(#maxRedirects, value),
    returnValueForMissingStub: null,
  );

  @override
  _i2.ByteStream finalize() =>
      (super.noSuchMethod(
            Invocation.method(#finalize, []),
            returnValue: _i6.dummyValue<_i2.ByteStream>(
              this,
              Invocation.method(#finalize, []),
            ),
          )
          as _i2.ByteStream);

  @override
  _i5.Future<_i2.StreamedResponse> send() =>
      (super.noSuchMethod(
            Invocation.method(#send, []),
            returnValue: _i5.Future<_i2.StreamedResponse>.value(
              _FakeStreamedResponse_5(this, Invocation.method(#send, [])),
            ),
          )
          as _i5.Future<_i2.StreamedResponse>);
}
